server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - name: CountFilter
      routes:
        - id: userRoute
          uri: http://localhost:8002/
          predicates:
            - Path=/users/**
          filters:
            - AddRequestHeader=user-request-header, testing-headers
            - AddResponseHeader=user-response-header, testing-response-header
        - id: productRoute
          uri: http://localhost:8004/
          predicates:
            - Path=/products/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway